# Generated by Django 2.1.7 on 2019-03-18 15:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import localflavor.generic.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0032_auto_20190116_1552'),
        ('humanresources', '0060_auto_20190116_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('ext_person_name', models.CharField(blank=True, max_length=80, verbose_name='Name')),
                ('ext_person_iban', localflavor.generic.models.IBANField(blank=True, include_countries=('PT',), max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.FinanceCostCenter')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='humanresources.Person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.FinanceProject')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='reimbursements.Reimbursement'),
        ),
    ]
