# Generated by Django 2.1.7 on 2019-03-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0004_reimbursement_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='cost_center',
        ),
    ]
