# Generated by Django 2.2 on 2019-04-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0005_remove_reimbursement_cost_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement',
            old_name='ext_person_iban',
            new_name='iban',
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='ext_person_name',
        ),
    ]
