# Generated by Django 2.2 on 2019-04-11 18:27

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0006_auto_20190411_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Document number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='requisition_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Requisition number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(djmoney.money.Money(0.01))], verbose_name='Currency'),
        ),
    ]
