# Generated by Django 2.2 on 2019-04-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0007_auto_20190411_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ('-created',), 'permissions': (('can_approve', 'Approve or reject Reimbursements'),)},
        ),
    ]
