# Generated by Django 2.2 on 2019-04-11 22:47

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0010_auto_20190411_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(djmoney.money.Money(0.01))], verbose_name='Amount'),
        ),
    ]
