# Generated by Django 2.2 on 2019-05-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0032_auto_20190116_1552'),
        ('reimbursements', '0011_auto_20190411_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expensecode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_expenses', to='supplier.ExpenseCode'),
            preserve_default=False,
        ),
    ]
