# Generated by Django 2.2 on 2019-05-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0012_expense_expensecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expensecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_expenses', to='supplier.ExpenseCode', verbose_name='Expense code'),
        ),
    ]
