# Generated by Django 2.2 on 2019-05-22 10:35

from django.db import migrations, models
import reimbursements.models.expense


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0013_auto_20190522_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(default=None, upload_to=reimbursements.models.expense.user_directory_path, verbose_name='Receipt'),
            preserve_default=False,
        ),
    ]
