# Generated by Django 2.2 on 2019-05-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0014_expense_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='project',
        ),
    ]
