# Generated by Django 2.2 on 2019-05-22 16:46

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0015_remove_reimbursement_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_social',
            field=models.BooleanField(default=False, verbose_name='Is a social expense'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
