# Generated by Django 2.2 on 2019-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0016_auto_20190522_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_date',
            field=models.DateField(default=None, null=True, verbose_name='Receipt date'),
        ),
    ]
