# Generated by Django 2.2 on 2019-05-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0032_auto_20190116_1552'),
        ('reimbursements', '0017_expense_receipt_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('document_number',)},
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Order'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_social',
            field=models.BooleanField(default=False, verbose_name='It is a social expense'),
        ),
    ]
