# Generated by Django 2.2 on 2019-05-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0018_auto_20190522_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ('-created',), 'permissions': (('manage_reimbursements', 'Submit reimbursements for approval'), ('can_approve_reimbursements', 'Approve or reject reimbursements'), ('receive_approved_notifications', 'Receive notifications about the approved reimbursements')), 'verbose_name': 'Reimbursement', 'verbose_name_plural': 'Reimbursements'},
        ),
        migrations.AddField(
            model_name='expense',
            name='eur_value',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Amount in euros'),
            preserve_default=False,
        ),
    ]
