# Generated by Django 2.2 on 2019-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0019_auto_20190523_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='eur_value',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount in EUR'),
        ),
    ]
