# Generated by Django 2.2.2 on 2019-06-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0020_auto_20190523_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='bank_transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transfer date'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='humanresources.Person'),
            preserve_default=False,
        ),
    ]
