# Generated by Django 2.2.1 on 2019-06-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0021_auto_20190606_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('document_number',), 'verbose_name': 'Reimbursement expense', 'verbose_name_plural': 'Reimbursements expenses'},
        ),
    ]
