# Generated by Django 2.2.1 on 2019-09-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0023_auto_20190911_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ('-created',), 'permissions': (('create_reimbursements_on_behalf_others', 'Create new reimbursements on behalf name of others'), ('manage_reimbursements', 'Submit reimbursements for approval'), ('can_approve_reimbursements', 'Approve or reject reimbursements'), ('receive_approved_notifications', 'Receive notifications about the approved reimbursements')), 'verbose_name': 'Reimbursement', 'verbose_name_plural': 'Reimbursements'},
        ),
    ]
