# Generated by Django 2.2.1 on 2019-09-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0025_perdiem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name'),
        ),
    ]
