# Generated by Django 2.2.1 on 2019-09-13 15:39

from django.db import migrations, models
import reimbursements.models.expense.expense


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0029_auto_20190913_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=reimbursements.models.expense.expense.user_directory_path, verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Receipt date'),
        ),
    ]
