# Generated by Django 2.2.1 on 2019-09-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0030_auto_20190913_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reimbursements.Expense')),
                ('purpose', models.CharField(max_length=255, verbose_name='Travel purpose')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('distance', models.PositiveSmallIntegerField(verbose_name='Distance in Km')),
            ],
            bases=('reimbursements.expense',),
        ),
    ]
