# Generated by Django 2.2.1 on 2019-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursements', '0031_carexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carexpense',
            name='local',
            field=models.CharField(default=1, max_length=255, verbose_name='Local'),
            preserve_default=False,
        ),
    ]
